version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file GetCustomerReport.yaml --s3-bucket codepipeline-us-east-2-842717197011
                                   --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - GetCustomerReport.yaml
    - outputSamTemplate.yaml